### PR TITLE
fix: Fix input and form handling in edit dialog

### LINKED ISSUE #31: Using Mapeo Webmaps/  can't save (screen freezes) the edits made in the "Map title" and "Map description" fields
**Describe the bug**
 I've done more testing and surprisingly you can edit the title and description fields if you also edit the "Terms & Limitations" field, Otherwise you can't save the changes... I don't think this is intended behavior.

**Can you do the same thing twice?**
The exact steps to see the problem again.
1. Go to '[https://maps.mapeo.app/](https://maps.mapeo.app/)"
2. Click on 'ADD MAP" and select a .mapeomap file
3. In the menu of the added map, click on "Edit Map details"
4. Make some changes in the "Map title" and "Map Description" fields

1. Click on "Save" to save the changes
2. See that nothing is happening. The screen freezes.
3. If you press anywhere outside the edit window you can reopen the edit window and will see that no changes have been changed. The same happens if you exit the page and enter again.
4. If you edit first the field "Terms & limitations" then you are able to edit and save the other fields without any problem
5.

**Expected behavior**
Edits made in both "Map title" and "Map description" fields should be saved when clicking on the "Save" button

**Screenshots**
Frozen screen that appears after editing "title" and "description" fields and clicking on "save"
https://www.notion.so/digidem/QA-Script-MAPEO-Desktop-v5-4-Observation-Mar-3d55ee3d3c184410a726eb5337c350a6#e5b4d47595e647f095f9591b9b17d5e3

8 points
**Desktop:**
 version: v.5.4.0 beta 15
language: ESP
config: ECA Amarakaeri: mapeo-config-amarakaeri-v3.1.1 // Default

### PR DESCRIPTION
**Pull request by achou11**
Fixes #31 

---

Preview:

31-mapeo-web-edit

### CODE REVIEW

File: src/EditDialog.js [hunk 1]
```diff
@@ -160,58 +181,37 @@ export default function EditDialog({ open, id, onClose }) {
...
             label={formatMessage(msgs.title_label)}
-            value={
-              value === undefined
-                ? ""
-                : title === undefined
-                ? value.title
-                : title
-            }
+            value={title}
+            InputLabelProps={{ shrink: !!title }}
```
Comment (achou11) [inline src/EditDialog.js:185]: necessary to prevent the floating label from overlapping with a non-empty input value (see [docs](https://v4.mui.com/components/text-fields/#shrink))

**Comment by ErikSin** [comment]
Can you explain original problem, and your fix, from a technical point of view?

**Comment by achou11** [comment]
> Can you explain original problem, and your fix, from a technical point of view?

Yeah so the original problem was that when editing the details of an uploaded map (such as the title, description, terms/conditions, or map style), the app would throw an error when attempting to save any changes. This is because when saving these details, there would be cases where we'd attempt to save an object field with a value of `undefined`, which is not a valid document field value for Firebase. The fix is to instantiate all of the fields as empty strings and ensure that we're never attempting to save a value of `undefined` to firebase.

We could theoretically save the fields as `null` but it doesn't look like we do any strict checks for that value in the app, so I figured that an empty string as the default empty value would be sufficient and easier to understand

File: src/EditDialog.js [hunk 2]
```diff
@@ -110,6 +111,26 @@ export default function EditDialog({ open, id, onClose }) {
...
+      if (value.terms) {
+        setTerms(value.terms);
+      }
+
+      if (value.mapStyle) {
+        setMapStyle(value.mapStyle);
+      }
+    }
+  }, [value]);
+
```
Comment (ErikSin) [inline src/EditDialog.js:133]: Im pretty sure this is redundant if you are using `onChange={e=>setState(e.target.value)}` on the `textfields`

**Comment by ErikSin** [comment]
> > Can you explain original problem, and your fix, from a technical point of view?
> 
> Yeah so the original problem was that when editing the details of an uploaded map (such as the title, description, terms/conditions, or map style), the app would throw an error when attempting to save any changes. This is because when saving these details, there would be cases where we'd attempt to save an object field with a value of `undefined`, which is not a valid document field value for Firebase. The fix is to instantiate all of the fields as empty strings for a default value and ensure that we're never attempting to save a value of `undefined` to firebase.
> 
> We could theoretically save the fields as `null` but it doesn't look like we do any strict checks for that value in the app, so I figured that an empty string as the default empty value would be sufficient and easier to understand

Thanks Andrew, makes sense!

File: src/EditDialog.js (hunk 2 above)
Comment (achou11) [reply src/EditDialog.js:133]: this is for the initialization of the text fields. The `value` refers to the map metadata that's retrieved from firebase

Comment (ErikSin) [reply src/EditDialog.js:133]: Ahhh right, gotcha!

**Review by ErikSin — APPROVED** [review]

**Review by gmaclennan — APPROVED** [review]
Looks good to me. Yet another reminder that we should settle on a form library to abstract some of this work - there is so much boilerplate involved in a form like this and so many little bugs that can go wrong. Can we review options on one of our calls?

**Comment by achou11** [comment]
> Can we review options on one of our calls?

I'll bring it up to Ximena about adding to one of our tech discussions
